profile:
  env: "dev"

app:
  addr: "localhost:8080"

db:
  # sslmode=disable 用于开发环境，线上一般推荐使用 sslmode=require / sslmode=verify-ca(更高安全性) / sslmode=verify-full (最高安全性)
  dsn: "postgres://jrmarcco:%3Cpasswd%3E@192.168.3.3:5432/kuryr_admin?sslmode=disable&connect_timeout=1&statement_timeout=3000&idle_in_transaction_session_timeout=3000"

redis:
  addr: 192.168.3.3:6379
  password: "<passwd>"

cors:
  # 单位（秒）
  max_age: 86400
  hostnames:
    - "localhost"

jwt:
  private: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEINuchwbkYeYD/jnGLyPjRAufQGP+WUckh+PK6U4u7fk1
    -----END PRIVATE KEY-----
  public: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEA818wiIDR2aqxvLKcyQL2qvVCYlSs2A/izQi/K109rlU=
    -----END PUBLIC KEY-----
  access:
    expiration: 1800 # Access Token 过期时间，单位：秒 (例如 30 分钟)
    issuer: "kuryr-admin-access"
  refresh:
    expiration: 604800 # Refresh Token 过期时间，单位：秒 (例如 7 天)
    issuer: "kuryr-admin-refresh"

ignores:
  - "/api/v1/user/login"
  - "/api/v1/user/refresh_token"

session:
  expiration: 604800 # 推荐和 refresh token 的过期时间一致

etcd:
  endpoints:
    - "192.168.3.3:52379"
    - "192.168.3.3:52381"
    - "192.168.3.3:52383"
  username: "root"
  password: "<root_passwd>"
  dial_timeout: 1000  # 单位：毫秒
  tls:
    enabled: true
    cert_file: "etc/etcd-certs/client.pem"
    key_file: "etc/etcd-certs/client-key.pem"
    ca_file: "etc/etcd-certs/ca.pem"
    insecure_skip_verify: false

registry:
  lease_ttl: 30 # 单位：秒，这里和 etcd api 保持一直所以是秒单位

load_balance:
  name: "read_write_weight"
  timeout: 3000                       # 单位：毫秒
  keep_alive:
    time: 600000                      # 单位：毫秒
    timeout: 10000                    # 单位：毫秒
    permit_without_stream: true
