profile:
  env: "dev"

app:
  addr: ":8080"

db:
  dsn: "jrmarcco:<passwd>@tcp(192.168.3.3:3306)/kuryr_admin?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true&interpolateParams=true"

redis:
  addr: 192.168.3.3:6379
  password: "<passwd>"

cors:
  # 单位（秒）
  max_age: 86400
  hostnames:
    - "localhost"

jwt:
  private: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEINuchwbkYeYD/jnGLyPjRAufQGP+WUckh+PK6U4u7fk1
    -----END PRIVATE KEY-----
  public: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEA818wiIDR2aqxvLKcyQL2qvVCYlSs2A/izQi/K109rlU=
    -----END PUBLIC KEY-----
  access:
    expiration: 3600 # Access Token 过期时间，单位：秒 (例如 1 小时)
    issuer: "kuryr-admin-access"
  refresh:
    expiration: 604800 # Refresh Token 过期时间，单位：秒 (例如 7 天)
    issuer: "kuryr-admin-refresh"

ignores:
  - "/api/v1/user/login"
  - "/api/v1/user/refresh_token"

session:
  expiration: 604800 # 推荐和 refresh token 的过期时间一致
